version: '3'

services:
  db:
    container_name: postgres-data
    image: postgres:15.1
    ports:
      - ${PORT_DB}:${PORT_DBA}
    volumes:
      - postgres-db:/var/lib/postgresql/data
      #- ./postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - ${PORT_PGA}:${PORT_PGB}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}

volumes:
  postgres-db:
    external: true